spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/sd-project
spring.datasource.username=sd-project
spring.datasource.password=1234
spring.sql.init.platform=postgres

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

jwt.secret=VGhpcy1pcy1hLXZlcnktc2VjcmV0LWtleS1mb3Itand0LWFzc2lnbm1lbnQtMw==

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.mail.from=${MAIL_USERNAME}